services:
  api:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [redis]
  worker1:
    build: .
    command: celery -A app.tasks.analyze_task.celery_app worker --loglevel=INFO
    env_file: .env
    depends_on: [redis]
  worker2:
    build: .
    command: celery -A app.tasks.analyze_task.celery_app worker --loglevel=INFO
    env_file: .env
    depends_on: [redis]
  redis:
    image: redis:7-alpine
